### ISSUE TITLE
Missing page.xml file causes internal server error

### ISSUE THREAD

**Issue by notsure** [sulu-io/sulu-standard#415] opened 2015-02-23 13:19 UTC
Given is, that you have added at least one page in the content area of a webspace.
The page uses a custom template which is set by the user in admin interface. 

Now if this linked template is deleted and a user wants to browse the webspace section in the cms an internal server error occurs and the page is not loaded.

```
http://pool-alpin.lo/admin/#content/contents/
````

This is going to be a major problem when changing or refactoring the structure of a webspace and update it to a existing and / or running system. As you can no longer use the admin interface to change the page template.

**Comment by notsure** [comment] 2015-02-23 13:29
https://github.com/sulu-cmf/sulu/issues/228

**Comment by danrot** [comment] 2015-02-25 19:12
So this is a duplicate of the issue you have mentioned? If yes, please mark this as duplicate and close it.

**Comment by wachterjohannes** [comment] 2015-02-26 07:01
@danrot no it is not the same but related! the over is when you create a page and delete the template!

**Comment by danrot** [comment] 2015-10-07 15:35
I know this comment is quite old, but I can't see how these two issues are not the same. I would close this one in favor of the one in sulu/sulu, but I still don't really know how to tackle this problem...

Or can you explain me in which way these two issues are different? The system is trying to load a page with a template that does not exist anymore, what obviously happens if it existed before but was deleted.

**Closed** 2015-10-08 09:11 UTC
Labels: Bug
