### ISSUE TITLE
URL on changed template is wrong

### ISSUE THREAD

**Issue by dmetzler1988** [sulu-io/sulu-standard#524] opened 2015-10-02 06:38 UTC
Steps to reproduce it:
1. create new subpage with default template
2. edit title and url (resourcelocator)
3. change template-type
4. add title and url again

now the url is not correct.

wrong example (missing "smile-award/" in front or url):
![bildschirmfoto 2015-10-02 um 08 36 26](https://cloud.githubusercontent.com/assets/8446518/10240815/ead48602-68e0-11e5-9ee4-cbe62da7eb23.png)

correct example:
![bildschirmfoto 2015-10-02 um 08 37 36](https://cloud.githubusercontent.com/assets/8446518/10240818/f796cfc6-68e0-11e5-8242-4020c023f325.png)

**Comment by danrot** [comment] 2015-10-05 11:39
That's a duplicate of https://github.com/sulu-io/sulu/issues/926.

**Closed by danrot** 2015-10-05 11:39 UTC
Labels: duplicate
